### PR TITLE
Fixes Sort with multiple fields

### PR DESCRIPTION
**Pull request by barata0**
Added more test cases for sort with 3 names and 2 props, and 3 names and 3 props.
Fixed the sort algorithm

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for the pull request. I'm wondering if we should just copy the sorting mechanism from Nedb (https://github.com/louischatriot/nedb/blob/master/lib/model.js#L189) so that it is as close as possible to how at least many of the database adapters work.

Maybe an additional alternative syntax like `[ [ 'name', 1 ], [ 'age': -1 ] ]` that enforces a precedence also might make sense here.

**Comment by barata0** [comment]
Hi,

About the syntax I believe its fine 

I forgot to link the issue I created about this where I explain the strange behavior sorting multiple fields, 
[https://github.com/feathersjs/commons/issues/74](https://github.com/feathersjs/commons/issues/74)

I noticed this problem on *fetahers-vuex* as well
[https://github.com/feathers-plus/feathers-vuex/issues/103](https://github.com/feathers-plus/feathers-vuex/issues/103)


how to reproduce: Based on the test array at _test\utils.test.js_ I just added another name (Andrew) and the problem happens

```
var commons = require('@feathersjs/commons')

var array = [
  {name: 'David', counter: 0 },
  {name: 'Eric', counter: 1},
  {name: 'Andrew', counter: 1},
  {name: 'David', counter: 1},
  {name: 'Andrew', counter: 0},
  {name: 'Eric', counter: 0}
];

var sort = commons.sorter({
  name: -1,
  counter: 1
});

array.sort(sort)

```
[ { name: 'Eric', counter: 0, _id: 'SlRlGP80a9CmPsh6' },
  { name: 'Eric', counter: 1, _id: 'vhibqPV085Lk0pkh' },
  { name: 'David', counter: 0, _id: 'otdiZrNc7ftQJtK5' },
  { name: 'David', counter: 1, _id: 'rKZDfXqwMftRSajG' },
  { name: 'Andrew', counter: 0, _id: 'JlaXbp9b8G9pDACE' },
  { name: 'Andrew', counter: 1, _id: 'NraNQqDRHhpQTzH7' } ]
The result has no sort order at all

```
[ { name: 'Andrew', counter: 0 },
  { name: 'David', counter: 0 },
  { name: 'Andrew', counter: 1 },
  { name: 'David', counter: 1 },
  { name: 'Eric', counter: 0 },
  { name: 'Eric', counter: 1 } ]
```

Ps.
I tested with neDB. after inserting the same documents and running

```
var dbResult = db.find({}).sort({ name: -1, counter: 1}).exec(function (err, docs) {
```

I got the expected result (with neDB)

```
[ { name: 'Eric', counter: 0, _id: 'SlRlGP80a9CmPsh6' },
  { name: 'Eric', counter: 1, _id: 'vhibqPV085Lk0pkh' },
  { name: 'David', counter: 0, _id: 'otdiZrNc7ftQJtK5' },
  { name: 'David', counter: 1, _id: 'rKZDfXqwMftRSajG' },
  { name: 'Andrew', counter: 0, _id: 'JlaXbp9b8G9pDACE' },
  { name: 'Andrew', counter: 1, _id: 'NraNQqDRHhpQTzH7' } ]
```

**Comment by daffl** [comment]
I think using NeDB's sorting code to fix this problem properly makes the most sense then. Do you want to update your PR accordingly?

**Comment by daffl** [comment]
Thanks again for the pull request. I used your branch and made the suggested changes to use NeDB's sorting in https://github.com/feathersjs/commons/pull/76. Released in v1.4.2

**Pull request closed without merging**
