### PR TITLE
Open hook workflow to custom methods

### PR DESCRIPTION
**Pull request by bertho-zero**
This PR allows you to add converters to your custom methods, which allows to create the hook corresponding to your arguments and finally to fully use the hook workflow.

I would have liked to use a Symbol but https://github.com/feathersjs/feathers/issues/863.

Example:
```js
const app = feathers().use('/dummy', {
  methods: {
    custom: ['id', 'data', 'params']
  },
  get() {},
  // ...
  custom(id, data, params) {
    return Promise.resolve([id, data, params]);
  }
});

app.service('dummy').hooks({
  before: {
    all: [/**/],
    custom: [/**/]
  },
  after: {
    all: [/**/],
    custom: [/**/]
  }
});

app.service('dummy').custom(28, { bar: 'foo' }, { provider: 'rest' });
```

### CODE REVIEW

**Comment by daffl** [comment]
This is great, thank you! I was actually thinking about doing the same thing for #853. I'm not sure if the converters are needed. I was going to put the arguments array for unknown methods into `hook.arguments`.

**Comment by bertho-zero** [comment]
I chose the simplest solution, the one used internally but it's true that converters can easily be translated from `['id', 'data', 'params']`.

I do not know where exactly you would like to declare `hook.arguments`?

**Comment by bertho-zero** [comment]
Do you think of something like this?

```js
const app = feathers().use('/dummy', {
  methods: {
    custom: ['id', 'data', 'params']
  },
  get() {},
  // ...
  custom(id, data, params) {
    return Promise.resolve([id, data, params]);
  }
});

app.service('dummy').hooks({
  before: {
    all: [/**/],
    custom: [/**/]
  },
  after: {
    all: [/**/],
    custom: [/**/]
  }
});

return app.service('dummy').custom(28, { bar: 'foo' }, { provider: 'rest' });
```

or

```js
const app = feathers().use('/dummy', {
  methods: ['custom'],
  get() {},
  // ...
  custom(id, data, params) {
    return Promise.resolve([id, data, params]);
  }
});

app.service('dummy').hooks({
  arguments: {
    custom: ['id', 'data', 'params']
  }
  before: {
    all: [/**/],
    custom: [/**/]
  },
  after: {
    all: [/**/],
    custom: [/**/]
  }
});

return app.service('dummy').custom(28, { bar: 'foo' }, { provider: 'rest' });
```

**Comment by bertho-zero** [comment]
I have updated the first example.

**Comment by bertho-zero** [comment]
I do not see exactly what changes I should make based on your comment, can you point me?

**Comment by bertho-zero** [comment]
I have updated this and https://github.com/feathersjs/feathers/pull/864.

**Comment by bertho-zero** [comment]
I deleted converters, it's a hook that is just after `validateHook` that adds arguments for each method.
And I also modified `validateArguments` to validate all methods.

**Comment by daffl** [comment]
This looks great, thank you! I'll get this one in and then verify it against https://github.com/feathersjs/feathers/pull/864

**Pull request merged**
